var ns = [5, 6, 7, 8];
console.log(typeof ns);
console.log(ns);
// let ns= [5,6,7,8];
// console.log(typeof ns);
// console.log(ns);
// let names:readonly string[] = ["Dara"];
// names.push("Thida");
// names.push(5);
// console.log(names);
